---
  apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata: 
    name: "prometheus"
    namespace: "default"
  spec: 
    replicas: 1
    template: 
      metadata: 
        labels:
          app: prometheus
      spec: 
        containers: 
          - name: "prometheus"
            image: "quay.io/andysmith/prometheus"
            args: [
              "-config.file=/prometheus/prometheus.yml"
            ]	
            ports: 
              - containerPort: 9090
                protocol: "TCP"
            imagePullPolicy: "IfNotPresent"
            volumeMounts:
              - name: prometheus
                mountPath: /prometheus/
        restartPolicy: "Always"
        dnsPolicy: "ClusterFirst"
        volumes:
          - name: prometheus
            configMap:
              name: prometheus
              

